### PR TITLE
Add fix for count filter in data series query

### LINKED ISSUE #21955: Adding a "count: " filter breaks insights since we automatically attach a count filter anyway
Here's the query we try to run if you add a count filter – 

We should probably just default to your count filter. We (the extensibility team) just dealt with this on search-export, so perhaps a solution can be [grabbed from there](https://github.com/sourcegraph/sourcegraph-search-export/pull/8)?

image

### PR DESCRIPTION
**Pull request by vovakulikov**
Closes https://github.com/sourcegraph/sourcegraph/issues/21955

This PR adds logic for the data series query count filter and excludes adding the max count filter value 99999 if the count filter was specified in user search query. 

**Before** 

Screenshot 2021-06-14 at 12 07 24

**After**

Screenshot 2021-06-14 at 12 04 58

### CODE REVIEW

File: src/search-insights.ts [hunk 1]
```diff
@@ -341,3 +346,7 @@ async function determineCommitsToSearch(dates: Date[], repo: string): Promise<Se
 
     return commitOids
 }
+
+function getQueryWithCountFilter(query: string): string {
+    return queryHasCountFilter(query) ? query : `${query} count:99999`
```
Comment (valerybugakov) [inline src/search-insights.ts:351]: Curious, is it a backend issue that query errors without count argument or it's expected behaviour that's documented in the graphql schema?

**Review by valerybugakov — APPROVED** [review]

File: src/search-insights.ts (hunk 1 above)
Comment (vovakulikov) [reply src/search-insights.ts:351]: This is a good call. 
I just realized that we can use probably just count: all as default value for count filter

Here is a small description of the count filter from our search grammar doc
>Retrieve N results. By default, Sourcegraph stops searching early and returns if it finds a full page of results. This is desirable for most interactive searches. To wait for all results, use count:all.

Comment (vovakulikov) [reply src/search-insights.ts:351]: But I would prefer to merge this PR and move further here with search query syntax in separate story about query search input https://github.com/sourcegraph/sourcegraph/issues/21339
